students=[ 
    {
    "id":1,
    "name":"nishant",
    "age":19,
    "student_class":"11th"
    },
       {
    "id":2,
    "name":"nishu",
    "age":20,
    "student_class":"12th"
    },
       {
    "id":3,
    "name":"nisha",
    "age":15,
    "student_class":"9th"
    },
      {
    "id":1,
    "name":"nishant",
    "age":19,
    "student_class":"11th"
    },
       {
    "id":2,
    "name":"nishu",
    "age":20,
    "student_class":"12th"
    },
       {
    "id":3,
    "name":"nisha",
    "age":15,
    "student_class":"9th"
    },
      {
    "id":1,
    "name":"nishant",
    "age":19,
    "student_class":"11th"
    },
       {
    "id":2,
    "name":"nishu",
    "age":20,
    "student_class":"12th"
    },
       {
    "id":3,
    "name":"nisha",
    "age":15,
    "student_class":"9th"
    }
]